### ISSUE TITLE
Mercaderes

### ISSUE THREAD

**Issue by SantiGonzalezLago** [SantiGonzalezLago/LigaDeAventureros#11]
Debe haber 3 tipos de mercaderes:
- **Mercader permanente**. Tendrá una lista fija de objetos que estará siempre disponible. Estos objetos se podrán configurar desde el backend de Administrador.
- **Mercader aleatorio**. Tendrá una lista de objetos que irá rotando aleatoriamente entre los existentes en la base de datos. Desde el backend de Administrador se podrá configurar la frecuencia con la que cambia y la cantidad de objetos, pudiendo desglosar por rareza (p. ej., 2 very rare, 5 rare, 10 uncommon)
- **Mercader de evento**. Tendrá una lista fija de objetos que estará disponible durante determinados eventos. Desde el backend se podrá configurar en qué fechas estará activo (puede ser una sola vez o repetirse anualmente) y qué objetos tiene. Se podrán configurar varios mercaderes de evento y más de uno podrá estar activo simultaneamente.

Los jugadores podrán comprar directamente en el mercader, sin la intervención de un master.

También se creará un tablón de anuncios, donde los jugadores podrán poner a la venta objetos que no necesitan por un precio que pueden definir, otros jugadores podrán revisar el tablón y comprar lo que quieran.
Para evitar abusos, este sistema no permitirá transferencias entre personajes de un mismo jugador, y solo estará disponible para personajes que tengan una ficha validada.

**Comment by BVazquezAlvarez** [comment]
Hola! Supongo que sabes que hice un fork de este proyecto. Si precisas ayuda sobre este tema puedo echarte una mano. Al fin y al cabo tenía pensado hacer lo mismo y así nos ahorramos tiempo de desarrollo

**Comment by SantiGonzalezLago** [comment]
Disculpa la tardanza en responder. Estoy trabajando actualmente en esta tarea y espero tenerlo funcional hacia el final de esta semana. Si quieres puedes cogerlo a partir de ahí y revisar detalles que falten.
